version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.2.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate definition
          command: packer validate ./build.json
  build:
    docker:
      - image: hashicorp/packer:1.2.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build AMI
          command: ./build.sh
          no_output_timeout: 30m
workflows:
  version: 2
  commit:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only:
                - master
          context: packer
  monthly:
    triggers:
      - schedule:
          cron: "13 2 19 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - validate
      - build:
          requires:
            - validate